# Expose buildbot on http://localhost:8010/

---

x-base-service: &base-service
  build:
    context: ..
    dockerfile: docker/Dockerfile
  volumes:
    - sharedrepo:/sharedrepo
    - publish:/publish
    - mirror:/home/pokybuild/git/mirror
    - srvautobuilder:/srv/autobuilder
  stdin_open: true
  tty: true

services:
  controller:
    <<: *base-service
    ports:
      - 8010:8010
    cpus: 4
  worker: &base-worker
    <<: *base-service
    cpus: 8
    mem_limit: 16gb
  extraworker:
    <<: *base-worker
    cpus: 1
    mem_limit: 2gb
    deploy:
      replicas: 8
    profiles:
      - manyworkers

volumes:
  sharedrepo:
  publish:
  mirror:
  srvautobuilder:
