# Expose buildbot on http://localhost:8010/

---

services:
  controller:
    build: .
    volumes:
      - sharedrepo:/sharedrepo
      - publish:/publish
      - mirror:/home/pokybuild/git/mirror
      - srvautobuilder:/srv/autobuilder
    ports:
      - 8010:8010
    stdin_open: true
    tty: true
    cpus: 4
    command: controller
  worker:
    build: .
    volumes:
      - sharedrepo:/sharedrepo
      - publish:/publish
      - mirror:/home/pokybuild/git/mirror
      - srvautobuilder:/srv/autobuilder
    stdin_open: true
    tty: true
    cpus: 8
    command: worker yocto-worker
    mem_limit: 16gb

volumes:
  sharedrepo:
  publish:
  mirror:
  srvautobuilder:
